
Imports System.Windows.Forms
Imports BL
Imports DevExpress.XtraGrid.Views.Grid

Public Class SelectOrder

    Dim addcol As Integer = 0
    Public DT As New DataTable
    Dim N As Integer = 0
    Dim tempindex, i As Integer
    Dim col As New DataGridViewCheckBoxColumn  'Dim dt As New DataTable
    Public ENQname As String = ""  'for whereclause in fillgrid
    Public TEMPORNO As Integer
    Public PARTYNAME As String = ""
    Public FRMSTRING As String = ""



    Private Sub cmdexit_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdexit.Click
        Me.Close()
    End Sub

    Private Sub SelectOrder_KeyDown(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles MyBase.KeyDown
        If e.KeyCode = Windows.Forms.Keys.Escape Then
            Me.Close()
        ElseIf e.KeyCode = Keys.Enter Then
            SendKeys.Send("{Tab}")
        End If
    End Sub

    Private Sub SelectOrder_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        fillgrid()
    End Sub

    Sub fillgrid(Optional ByVal where As String = "")
        Try
            Cursor.Current = Cursors.WaitCursor
            If PARTYNAME <> "" Then where = where & " AND LEDGERS.Acc_cmpname='" & PARTYNAME & "'"

            Dim objcmn As New ClsCommon
            Dim dt As DataTable
            If FRMSTRING = "ASSEMBLY" Then
                GSUBITEM.Visible = False
                GDATE.Visible = False
                GSHIPTO.Visible = False
                GPONO.Visible = False

                'dt = objcmn.search(" CAST(0 AS BIT) AS CHK,  ISNULL(ALLORDERMASTER.ORDER_NO, '') AS ORDERNO, ISNULL(ALLORDERMASTER_DESC.ORDER_GRIDSRNO, '') AS ORDERSRNO, ISNULL(ITEMMASTER.item_code, '') AS ITEMCODE, ISNULL(ITEMMASTER.item_name, '') AS ITEMNAME, ISNULL(LEDGERS.Acc_cmpname, '') AS NAME, ISNULL(SHIPTOLEDGERS.Acc_cmpname, '') AS SHIPTO, ISNULL(ALLORDERMASTER.ORDER_PONO, '') AS PONO, ISNULL(ALLORDERMASTER_DESC.ORDER_QTY, 0) AS QUANTITY, ISNULL(ALLORDERMASTER.TYPE, '') AS ORDERTYPE ", "", " ALLORDERMASTER INNER JOIN ALLORDERMASTER_DESC ON ALLORDERMASTER.ORDER_NO = ALLORDERMASTER_DESC.ORDER_NO AND ALLORDERMASTER.ORDER_YEARID = ALLORDERMASTER_DESC.ORDER_YEARID LEFT OUTER JOIN LEDGERS AS SHIPTOLEDGERS ON ALLORDERMASTER.ORDER_SHIPTOID = SHIPTOLEDGERS.Acc_id LEFT OUTER JOIN LEDGERS ON ALLORDERMASTER.ORDER_LEDGERID = LEDGERS.Acc_id LEFT OUTER JOIN ITEMMASTER ON ALLORDERMASTER_DESC.ORDER_ITEMID = ITEMMASTER.item_id ", "  AND  ALLORDERMASTER.ORDER_YEARID=" & YearId & where & " and ALLORDERMASTER_DESC.ORDER_ASSEMBLYDONE = 0 AND ALLORDERMASTER_DESC.ORDER_CLOSE = 0 ORDER BY ALLORDERMASTER.ORDER_NO ")
                'dt = objcmn.search("*", "", " (SELECT DISTINCT CAST(0 AS BIT) AS CHK,  ALLORDERMASTER_DESC.ORDER_NO AS ORDERNO, ALLORDERMASTER_DESC.ORDER_GRIDSRNO AS ORDERSRNO, ALLORDERMASTER_DESC.TYPE AS ORDERTYPE, ITEMMASTER.item_code AS ITEMCODE, ITEMMASTER.item_name AS ITEMNAME, ALLORDERMASTER_DESC.ORDER_QTY AS QUANTITY, ALLORDERMASTER_DESC.ORDER_YEARID AS YEARID, LEDGERS.Acc_cmpname AS NAME FROM ALLORDERMASTER_DESC INNER JOIN  ALLORDERMASTER ON ALLORDERMASTER_DESC.ORDER_NO = ALLORDERMASTER.ORDER_NO AND ALLORDERMASTER_DESC.TYPE = ALLORDERMASTER.TYPE AND ALLORDERMASTER_DESC.ORDER_YEARID = ALLORDERMASTER.ORDER_YEARID  INNER JOIN LEDGERS ON ALLORDERMASTER.ORDER_LEDGERID = LEDGERS.Acc_id INNER JOIN ITEMMASTER ON ALLORDERMASTER_DESC.ORDER_ITEMID = ITEMMASTER.item_id LEFT OUTER JOIN ITEMMASTER_BOMDETAILS ON ITEMMASTER.item_id = ITEMMASTER_BOMDETAILS.ITEM_ID LEFT OUTER JOIN ITEMMASTER AS BOMITEMMASTER ON ITEMMASTER_BOMDETAILS.ITEM_SUBITEMID = BOMITEMMASTER.item_id INNER JOIN  BATCHMASTER ON JOBBATCH_ORDERNO = ALLORDERMASTER_DESC.ORDER_NO AND JOBBATCH_ORDERSRNO = ALLORDERMASTER_DESC.ORDER_GRIDSRNO AND JOBBATCH_ORDERTYPE = ALLORDERMASTER_DESC.TYPE AND JOBBATCH_YEARID = ALLORDERMASTER_DESC.ORDER_YEARID WHERE ALLORDERMASTER_DESC.ORDER_YEARID = " & YearId & where & "  AND ORDER_CLOSE = 0 ) AS FINALORDER ", " AND NOT EXISTS ( SELECT * FROM ( SELECT DISTINCT ORDERNO, ORDERSRNO, MAINITEMCODE, MAINITEMNAME, MAINITEMID, YEARID, ORDERTYPE FROM ( SELECT DISTINCT ORDER_NO AS ORDERNO, ORDER_GRIDSRNO AS ORDERSRNO, ALLORDERMASTER_DESC.TYPE AS ORDERTYPE, ITEMMASTER.ITEM_CODE AS MAINITEMCODE, ITEMMASTER.ITEM_NAME AS MAINITEMNAME, ITEMMASTER.ITEM_ID AS MAINITEMID, BOMITEMMASTER.ITEM_CODE AS BOMITEMCODE, BOMITEMMASTER.ITEM_NAME AS BOMITEMNAME, BOMITEMMASTER.ITEM_ID AS BOMITEMID, ALLORDERMASTER_DESC.ORDER_YEARID AS YEARID FROM ALLORDERMASTER_DESC INNER JOIN ITEMMASTER ON ORDER_ITEMID = ITEMMASTER.ITEM_ID INNER JOIN ITEMMASTER_BOMDETAILS ON ITEMMASTER.item_id = ITEMMASTER_BOMDETAILS.ITEM_ID INNER JOIN ITEMMASTER AS BOMITEMMASTER ON ITEMMASTER_BOMDETAILS.ITEM_SUBITEMID = BOMITEMMASTER.ITEM_ID WHERE ORDER_YEARID = " & YearId & ")  AS [ORDERMASTER] WHERE NOT EXISTS  (SELECT jobbatch_no AS JOBNO, JOBBATCH_ORDERNO AS SONO, JOBBATCH_ORDERSRNO AS SOSRNO, JOBBATCH_ORDERTYPE, jobbatch_itemid AS MAINTIEMID, JOBBATCH_SUBITEMID AS BOMITEMID, jobbatch_yearid AS YEARID FROM BATCHMASTER AS JOB WHERE jobbatch_yearid =" & YearId & "  AND jobbatch_madeqty > 0  AND JOBBATCH_ASSEMBLYDONE = 0 AND JOBBATCH_ORDERNO = ORDERMASTER.ORDERNO AND JOB.JOBBATCH_ORDERSRNO = ORDERMASTER.ORDERSRNO AND JOB.JOBBATCH_ORDERTYPE = ORDERMASTER.ORDERTYPE AND jobbatch_itemid = ORDERMASTER.MAINITEMID AND JOBBATCH_SUBITEMID = ORDERMASTER.BOMITEMID AND jobbatch_yearid = ORDERMASTER.YEARID) ) AS INCOMPLETEORDER WHERE  FINALORDER.ORDERNO = INCOMPLETEORDER.ORDERNO AND FINALORDER.ORDERSRNO = INCOMPLETEORDER.ORDERSRNO AND FINALORDER.ORDERTYPE = INCOMPLETEORDER.ORDERTYPE AND FINALORDER.YEARID = INCOMPLETEORDER.YEARID ) ")
                dt = objcmn.search("*", "", " (SELECT DISTINCT CAST(0 AS BIT) AS CHK,  ALLORDERMASTER_DESC.ORDER_NO AS ORDERNO, ALLORDERMASTER_DESC.ORDER_ASSEMBLYOUTQTY AS ASSEMBLYQTY, ALLORDERMASTER_DESC.ORDER_GRIDSRNO AS ORDERSRNO, ALLORDERMASTER_DESC.TYPE AS ORDERTYPE, ITEMMASTER.item_code AS ITEMCODE, ITEMMASTER.item_name AS ITEMNAME, ALLORDERMASTER_DESC.ORDER_QTY AS QUANTITY, ALLORDERMASTER_DESC.ORDER_YEARID AS YEARID, LEDGERS.Acc_cmpname AS NAME FROM ALLORDERMASTER_DESC INNER JOIN  ALLORDERMASTER ON ALLORDERMASTER_DESC.ORDER_NO = ALLORDERMASTER.ORDER_NO AND ALLORDERMASTER_DESC.TYPE = ALLORDERMASTER.TYPE AND ALLORDERMASTER_DESC.ORDER_YEARID = ALLORDERMASTER.ORDER_YEARID  INNER JOIN LEDGERS ON ALLORDERMASTER.ORDER_LEDGERID = LEDGERS.Acc_id INNER JOIN ITEMMASTER ON ALLORDERMASTER_DESC.ORDER_ITEMID = ITEMMASTER.item_id LEFT OUTER JOIN ITEMMASTER_BOMDETAILS ON ITEMMASTER.item_id = ITEMMASTER_BOMDETAILS.ITEM_ID LEFT OUTER JOIN ITEMMASTER AS BOMITEMMASTER ON ITEMMASTER_BOMDETAILS.ITEM_SUBITEMID = BOMITEMMASTER.item_id INNER JOIN  BATCHMASTER ON JOBBATCH_ORDERNO = ALLORDERMASTER_DESC.ORDER_NO AND JOBBATCH_ORDERSRNO = ALLORDERMASTER_DESC.ORDER_GRIDSRNO AND JOBBATCH_ORDERTYPE = ALLORDERMASTER_DESC.TYPE AND JOBBATCH_YEARID = ALLORDERMASTER_DESC.ORDER_YEARID WHERE ALLORDERMASTER_DESC.ORDER_YEARID = " & YearId & where & "  AND ORDER_CLOSE = 0 ) AS FINALORDER ", " AND NOT EXISTS ( SELECT * FROM ( SELECT DISTINCT ORDERNO, ORDERSRNO, MAINITEMCODE, MAINITEMNAME, MAINITEMID, YEARID, ORDERTYPE FROM ( SELECT DISTINCT ORDER_NO AS ORDERNO, ORDER_GRIDSRNO AS ORDERSRNO, ALLORDERMASTER_DESC.TYPE AS ORDERTYPE, ITEMMASTER.ITEM_CODE AS MAINITEMCODE, ITEMMASTER.ITEM_NAME AS MAINITEMNAME, ITEMMASTER.ITEM_ID AS MAINITEMID, BOMITEMMASTER.ITEM_CODE AS BOMITEMCODE, BOMITEMMASTER.ITEM_NAME AS BOMITEMNAME, BOMITEMMASTER.ITEM_ID AS BOMITEMID, ALLORDERMASTER_DESC.ORDER_YEARID AS YEARID FROM ALLORDERMASTER_DESC INNER JOIN ITEMMASTER ON ORDER_ITEMID = ITEMMASTER.ITEM_ID INNER JOIN ITEMMASTER_BOMDETAILS ON ITEMMASTER.item_id = ITEMMASTER_BOMDETAILS.ITEM_ID INNER JOIN ITEMMASTER AS BOMITEMMASTER ON ITEMMASTER_BOMDETAILS.ITEM_SUBITEMID = BOMITEMMASTER.ITEM_ID WHERE ORDER_YEARID = " & YearId & ")  AS [ORDERMASTER] WHERE NOT EXISTS  (SELECT jobbatch_no AS JOBNO, JOBBATCH_ORDERNO AS SONO, JOBBATCH_ORDERSRNO AS SOSRNO, JOBBATCH_ORDERTYPE, jobbatch_itemid AS MAINTIEMID, JOBBATCH_SUBITEMID AS BOMITEMID, jobbatch_yearid AS YEARID FROM BATCHMASTER AS JOB WHERE jobbatch_yearid =" & YearId & "  AND (jobbatch_madeqty > 0  OR JOBBATCH_ASSEMBLYDONE = 0) AND JOBBATCH_ORDERNO = ORDERMASTER.ORDERNO AND JOB.JOBBATCH_ORDERSRNO = ORDERMASTER.ORDERSRNO AND JOB.JOBBATCH_ORDERTYPE = ORDERMASTER.ORDERTYPE AND jobbatch_itemid = ORDERMASTER.MAINITEMID AND JOBBATCH_SUBITEMID = ORDERMASTER.BOMITEMID AND jobbatch_yearid = ORDERMASTER.YEARID) ) AS INCOMPLETEORDER WHERE  FINALORDER.ORDERNO = INCOMPLETEORDER.ORDERNO AND FINALORDER.ORDERSRNO = INCOMPLETEORDER.ORDERSRNO AND FINALORDER.ORDERTYPE = INCOMPLETEORDER.ORDERTYPE AND FINALORDER.YEARID = INCOMPLETEORDER.YEARID ) ")


            ElseIf FRMSTRING = "DILEVERY" Then
                GDATE.Visible = False
                GSUBITEM.Visible = False
                GASSEMBLYQTY.Visible = False

                ' dt = objcmn.search("  CAST(0 AS BIT) AS CHK, ISNULL(LEDGERS.Acc_cmpname, '') AS NAME, ISNULL(SHIPTOLEDGERS.Acc_cmpname, '') AS SHIPTO, ISNULL(ITEMMASTER.item_code, '') AS ITEMCODE, ISNULL(ITEMMASTER.item_name, '') AS ITEMNAME, ISNULL(ALLORDERMASTER.ORDER_PONO, '') AS PONO, ISNULL(UNITMASTER.unit_abbr, '') AS UNIT, ISNULL(ALLORDERMASTER_DESC.ORDER_QTY- ALLORDERMASTER_DESC.ORDER_DELOUTQTY, 0) AS QUANTITY, ISNULL(ALLORDERMASTER.ORDER_NO, 0) AS ORDERNO, ISNULL(ALLORDERMASTER_DESC.ORDER_GRIDSRNO, 0) AS ORDERSRNO, ISNULL(ALLORDERMASTER_DESC.TYPE, '') AS ORDERTYPE  ", "", " ALLORDERMASTER INNER JOIN ALLORDERMASTER_DESC ON ALLORDERMASTER.ORDER_NO = ALLORDERMASTER_DESC.ORDER_NO AND ALLORDERMASTER.ORDER_YEARID = ALLORDERMASTER_DESC.ORDER_YEARID LEFT OUTER JOIN UNITMASTER ON ALLORDERMASTER_DESC.ORDER_UNITID = UNITMASTER.unit_id LEFT OUTER JOIN ITEMMASTER ON ALLORDERMASTER_DESC.ORDER_ITEMID = ITEMMASTER.item_id LEFT OUTER JOIN LEDGERS AS SHIPTOLEDGERS ON ALLORDERMASTER.ORDER_SHIPTOID = SHIPTOLEDGERS.Acc_id LEFT OUTER JOIN LEDGERS ON ALLORDERMASTER.ORDER_LEDGERID = LEDGERS.Acc_id ", " AND (ALLORDERMASTER_DESC.ORDER_QTY - ALLORDERMASTER_DESC.ORDER_DELOUTQTY) > 0 AND  ALLORDERMASTER.ORDER_YEARID=" & YearId & where & " ORDER BY ALLORDERMASTER.ORDER_NO ")
                dt = objcmn.search("*", "", " (SELECT DISTINCT  CAST(0 AS BIT) AS CHK ,ISNULL(ALLORDERMASTER_DESC.ORDER_NO, 0) AS ORDERNO, ISNULL(ALLORDERMASTER_DESC.ORDER_GRIDSRNO, 0) AS ORDERSRNO, ALLORDERMASTER_DESC.TYPE AS ORDERTYPE ,ISNULL(LEDGERS.Acc_cmpname, '') AS NAME, ISNULL(SHIPTOLEDGERS.Acc_cmpname, '') AS SHIPTO, ISNULL(ALLORDERMASTER.ORDER_PONO, '') AS PONO, ISNULL(ITEMMASTER.item_code, '') AS ITEMCODE, ISNULL(ITEMMASTER.item_name, '') AS ITEMNAME, ISNULL(ALLORDERMASTER_DESC.ORDER_QTY, 0) AS QUANTITY,ISNULL(ALLORDERMASTER_DESC.ORDER_DELOUTQTY, 0) AS DELQTY, ALLORDERMASTER_DESC.ORDER_YEARID AS YEARID FROM  ALLORDERMASTER INNER JOIN ALLORDERMASTER_DESC ON ALLORDERMASTER_DESC.ORDER_NO = ALLORDERMASTER.ORDER_NO AND ALLORDERMASTER_DESC.ORDER_YEARID = ALLORDERMASTER.ORDER_YEARID AND  ALLORDERMASTER_DESC.TYPE = ALLORDERMASTER.TYPE INNER JOIN ITEMMASTER ON ALLORDERMASTER_DESC.ORDER_ITEMID = ITEMMASTER.item_id INNER JOIN ITEMMASTER_BOMDETAILS ON ITEMMASTER.item_id = ITEMMASTER_BOMDETAILS.ITEM_ID INNER JOIN ITEMMASTER AS BOMITEMMASTER ON ITEMMASTER_BOMDETAILS.ITEM_SUBITEMID = BOMITEMMASTER.item_id LEFT OUTER JOIN LEDGERS AS SHIPTOLEDGERS ON ALLORDERMASTER.ORDER_SHIPTOID = SHIPTOLEDGERS.Acc_id LEFT OUTER JOIN LEDGERS ON ALLORDERMASTER.ORDER_LEDGERID = LEDGERS.Acc_id WHERE ALLORDERMASTER.ORDER_YEARID = " & YearId & where & " AND ALLORDERMASTER_DESC.ORDER_CLOSE = 0 ) AS FINALORDER ", " AND NOT EXISTS ( SELECT * FROM ( SELECT DISTINCT ORDERNO, ORDERSRNO, MAINITEMCODE, MAINITEMNAME, MAINITEMID, YEARID FROM ( SELECT DISTINCT ORDER_NO AS ORDERNO, ORDER_GRIDSRNO AS ORDERSRNO, ITEMMASTER.ITEM_CODE AS MAINITEMCODE, ITEMMASTER.ITEM_NAME AS MAINITEMNAME, ITEMMASTER.ITEM_ID AS MAINITEMID, BOMITEMMASTER.ITEM_CODE AS BOMITEMCODE, BOMITEMMASTER.ITEM_NAME AS BOMITEMNAME, BOMITEMMASTER.ITEM_ID AS BOMITEMID, ALLORDERMASTER_DESC.ORDER_YEARID AS YEARID FROM ALLORDERMASTER_DESC INNER JOIN ITEMMASTER ON ORDER_ITEMID = ITEMMASTER.ITEM_ID INNER JOIN ITEMMASTER_BOMDETAILS ON ITEMMASTER.item_id = ITEMMASTER_BOMDETAILS.ITEM_ID INNER JOIN ITEMMASTER AS BOMITEMMASTER ON ITEMMASTER_BOMDETAILS.ITEM_SUBITEMID = BOMITEMMASTER.ITEM_ID WHERE ORDER_YEARID = " & YearId & ")  AS [ORDERMASTER] WHERE NOT EXISTS  (SELECT JOB_NO AS JOBNO, job_orderno AS SONO, job_ordersrno AS SOSRNO, JOB_MAINITEMID AS MAINTIEMID, JOB_SUBITEMID AS BOMITEMID, job_yearid AS YEARID FROM JOBBATCHMASTER AS JOB WHERE JOB_YEARID = " & YearId & " AND  JOB_ASSEMBLYQTY - JOB_DELOUTQTY > 0 AND JOB_FINISHED = 1 AND JOB.job_orderno = ORDERMASTER.ORDERNO AND JOB.job_ordersrno = ORDERMASTER.ORDERSRNO AND JOB.JOB_MAINITEMID = ORDERMASTER.MAINITEMID AND JOB.JOB_SUBITEMID = ORDERMASTER.BOMITEMID AND JOB.job_yearid = ORDERMASTER.YEARID)) AS INCOMPLETEORDER WHERE  FINALORDER.ORDERNO = INCOMPLETEORDER.ORDERNO AND FINALORDER.ORDERSRNO = INCOMPLETEORDER.ORDERSRNO AND FINALORDER.YEARID = INCOMPLETEORDER.YEARID)  ")

            Else
                dt = objcmn.search("CAST(0 AS BIT) AS CHK,ISNULL(ALLORDERMASTER.ORDER_NO, 0) AS ORDERNO, ISNULL(ALLORDERMASTER.ORDER_PONO, '') AS PONO, ISNULL(ALLORDERMASTER.TYPE, '') AS TYPE, ISNULL(ALLORDERMASTER_DESC.ORDER_GRIDSRNO, 0) AS ORDERSRNO, ISNULL(ALLORDERMASTER_DESC.ORDER_QTY - ALLORDERMASTER_DESC.ORDER_OUTQTY, 0) AS QUANTITY, ISNULL(LEDGERS.Acc_cmpname, '') AS NAME, ISNULL(ITEMMASTER.item_name, '') AS ITEMNAME, ISNULL(ITEMMASTER.item_code, '') AS ITEMCODE , ISNULL(SUBITEMMASTER.ITEM_CODE,'') AS SUBITEMCODE , SUBITEMMASTER.ITEM_ID", "", "ALLORDERMASTER INNER JOIN ALLORDERMASTER_DESC ON ALLORDERMASTER.ORDER_NO = ALLORDERMASTER_DESC.ORDER_NO AND ALLORDERMASTER.TYPE = ALLORDERMASTER_DESC.TYPE AND  ALLORDERMASTER.ORDER_YEARID = ALLORDERMASTER_DESC.ORDER_YEARID LEFT OUTER JOIN ITEMMASTER ON ALLORDERMASTER_DESC.ORDER_ITEMID = ITEMMASTER.item_id LEFT OUTER JOIN ITEMMASTER_BOMDETAILS ON ITEMMASTER_BOMDETAILS.ITEM_ID = ITEMMASTER.item_id LEFT OUTER JOIN ITEMMASTER AS SUBITEMMASTER ON ITEMMASTER_BOMDETAILS.ITEM_SUBITEMID = SUBITEMMASTER.item_id LEFT OUTER JOIN LEDGERS ON ALLORDERMASTER.ORDER_LEDGERID = LEDGERS.Acc_id", "AND ISNULL(ALLORDERMASTER_DESC.ORDER_QTY - ALLORDERMASTER_DESC.ORDER_OUTQTY, 0)>0 AND  ALLORDERMASTER.order_YEARID=" & YearId & " AND ISNULL(SUBITEMMASTER.ITEM_ID,0) NOT IN (SELECT JOB_SUBITEMID FROM JOBBATCHMASTER AS J WHERE J.job_yearid = " & YearId & " AND J.job_orderno=ALLORDERMASTER.ORDER_NO AND J.job_ordersrno=ALLORDERMASTER_DESC.ORDER_GRIDSRNO AND J.JOB_ORDERTYPE=ALLORDERMASTER.TYPE AND J.job_yearid=ALLORDERMASTER.ORDER_YEARID) ORDER BY ALLORDERMASTER.ORDER_NO, ORDER_GRIDSRNO")
            End If
            gridbilldetails.DataSource = dt
            If dt.Rows.Count > 0 Then
                gridbill.FocusedRowHandle = gridbill.RowCount - 1
                gridbill.TopRowIndex = gridbill.RowCount - 15
            End If
        Catch ex As Exception
            If ErrHandle(ex.Message.GetHashCode) = False Then Throw ex
        Finally
            Cursor.Current = Cursors.Default
        End Try
    End Sub

    Private Sub cmdok_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdok.Click
        Try
            If FRMSTRING = "ASSEMBLY" Then

                Dim COUNT As Integer = 0
                For i As Integer = 0 To gridbill.RowCount - 1
                    Dim dtrow As DataRow = gridbill.GetDataRow(i)
                    If Convert.ToBoolean(dtrow("CHK")) = True Then
                        COUNT = COUNT + 1
                    End If
                Next
                If COUNT > 1 Then
                    MsgBox("You Can Select Only One Batch")

                    Exit Sub
                End If

                DT.Columns.Add("ORDERNO")
                DT.Columns.Add("ORDERSRNO")
                DT.Columns.Add("QUANTITY")
                DT.Columns.Add("NAME")
                DT.Columns.Add("ITEMNAME")
                DT.Columns.Add("ITEMCODE")
                DT.Columns.Add("ORDERTYPE")

                For i As Integer = 0 To gridbill.RowCount - 1
                    Dim dtrow As DataRow = gridbill.GetDataRow(i)
                    If Convert.ToBoolean(dtrow("CHK")) = True Then
                        DT.Rows.Add(dtrow("ORDERNO"), dtrow("ORDERSRNO"), dtrow("QUANTITY"), dtrow("NAME"), dtrow("ITEMNAME"), dtrow("ITEMCODE"), dtrow("ORDERTYPE"))
                    End If
                Next

                Me.Close()


            ElseIf FRMSTRING = "DILEVERY" Then

                Dim COUNT As Integer = 0
                For i As Integer = 0 To gridbill.RowCount - 1
                    Dim dtrow As DataRow = gridbill.GetDataRow(i)
                    If Convert.ToBoolean(dtrow("CHK")) = True Then
                        COUNT = COUNT + 1
                    End If
                Next
                If COUNT > 1 Then
                    MsgBox("You Can Select Only One Order")

                    Exit Sub
                End If

                DT.Columns.Add("ORDERNO")
                DT.Columns.Add("ORDERSRNO")
                DT.Columns.Add("QUANTITY")
                DT.Columns.Add("NAME")
                DT.Columns.Add("ITEMNAME")
                DT.Columns.Add("ITEMCODE")
                DT.Columns.Add("ORDERTYPE")
                DT.Columns.Add("DELQTY")


                For i As Integer = 0 To gridbill.RowCount - 1
                    Dim dtrow As DataRow = gridbill.GetDataRow(i)
                    If Convert.ToBoolean(dtrow("CHK")) = True Then
                        DT.Rows.Add(dtrow("ORDERNO"), dtrow("ORDERSRNO"), dtrow("QUANTITY"), dtrow("NAME"), dtrow("ITEMNAME"), dtrow("ITEMCODE"), dtrow("ORDERTYPE"), dtrow("DELQTY"))
                    End If
                Next

                Me.Close()

            Else

                Dim COUNT As Integer = 0
                For i As Integer = 0 To gridbill.RowCount - 1
                    Dim dtrow As DataRow = gridbill.GetDataRow(i)
                    If Convert.ToBoolean(dtrow("CHK")) = True Then
                        COUNT = COUNT + 1
                    End If
                Next

                If COUNT > 1 Then
                    MsgBox("You Can Select Only One Order")

                    Exit Sub
                End If

                DT.Columns.Add("PONO")
                DT.Columns.Add("ORDERNO")
                DT.Columns.Add("ORDERSRNO")
                DT.Columns.Add("TYPE")
                DT.Columns.Add("SUBITEMCODE")
                For i As Integer = 0 To gridbill.RowCount - 1
                    Dim dtrow As DataRow = gridbill.GetDataRow(i)
                    If Convert.ToBoolean(dtrow("CHK")) = True Then
                        DT.Rows.Add(dtrow("PONO"), dtrow("ORDERNO"), dtrow("ORDERSRNO"), dtrow("TYPE"), dtrow("SUBITEMCODE"))
                    End If
                Next

                Me.Close()
            End If


        Catch ex As Exception
            Throw ex
        End Try
    End Sub

End Class